### ISSUE TITLE
RSS feed.

### ISSUE THREAD

**Issue by egecelikci** [eggsydev/eggsy-website#1]
It would be pretty cool if you add [RSS feed](https://en.wikipedia.org/wiki/RSS) to your website, I think you can use [@nuxtjs/feed](https://www.npmjs.com/package/@nuxtjs/feed). And since you're using [@nuxt/content](https://www.npmjs.com/package/@nuxt/content) I think [this](https://content.nuxtjs.org/integrations/#nuxtjsfeed) might help you.

**Comment by eggsydev** [comment]
Added with [29e2527](https://github.com/eggsydev/eggsy-website/commit/29e2527d685c0b996d97b8f3a493e9434e6a8038). Thanks for the suggestion, I also found that I can display blog posts in sitemap.xml in the same document you sent 💙
